import MySQLdb

# GLOBAL VARIABLES
HOST = '' #INSERT THE NAME OF YOUR HOST
USER = '' #INSERT YOUR USERNAME
PASSWORD = '' #INSERT YOUR PASSWORD
DB = '' #INSERT DATABASE NAME

db = MySQLdb.connect(host=HOST, user=USER, passwd=PASSWORD, db=DB)